language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - 3.4
    - 3.5

script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean install

after_success:
  - cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy --settings $HOME/.m2/settings.xml